### PR TITLE
Migrate @mui/x-date-pickers to v6

### LINKED ISSUE #2137: JSONForms >= 3.0.0 is incompatible with @mui/x-date-pickers >= 6.0.0
### Describe the bug

JSONForms >= 3.0.0 crashes when used with @mui/x-date-pickers >= 6.0.0.

### Expected behavior

JSONForms >= 3.0.0 should not crash when used with @mui/x-date-pickers >= 6.0.0.

### Steps to reproduce the issue

1. Go to [https://codesandbox.io/s/jsonforms-with-v6-mui-date-pickers-b8mkzm](https://codesandbox.io/s/jsonforms-with-v6-mui-date-pickers-b8mkzm)
1. Click on DatePicker calendar button
1. See error

### Screenshots

_No response_

### In which browser are you experiencing the issue?

Google Chrome 113.0.5672.92 (Official Build) (64-bit)

### Which Version of JSON Forms are you using?

v3.0.0

### Framework

React

### RendererSet

Material

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sebastianfrey**
Resolves #2137.

There are some things to consider:

1. Because @mui/date-pickers v6 relies on a newer version of @mui/base I had to upgrade @mui/material to a more recent version (v5.13.0).
1. There are no public types for the functional ActionBar API, so I had to introduce a custom interface to satisfy TS.
1. The input handling of the date picker components was reworked from the ground up in v6. For more details see [here](https://mui.com/blog/mui-x-v6/#date-and-time-pickers-features-highlights-%E2%9C%A8). For that reason I had to drop the custom `<ResetableTextField />` component and the custom text input value handling. Both were introduced in #1949. Unfortunately, as I understand the MUI release blog article correctly, there is no way at the moment to disable the masked input behavior. That means the behavior introduced in #1949 cannot be replicated with v6.

### CODE REVIEW

**Comment by sebastianfrey** [comment]
I have noticed, that the [Netlify prerview for materia renderers](https://deploy-preview-2139--jsonforms-examples.netlify.app/react-material/) does not work. It seems that in that deployment an older version of @mui is used.

**Comment by lucas-koehler** [comment]
> I have noticed, that the [Netlify prerview for materia renderers](https://deploy-preview-2139--jsonforms-examples.netlify.app/react-material/) does not work. After checking the browser console logs I encountered the following error:
> 
> ```
> react-dom.production.min.js:216 TypeError: useEnhancedEffectExports is not a function
>     at usePickerViews (usePickerViews.js:100:3)
> ```
> 
> It seems that the Netlify deployment uses an older version of @mui than specified in the dependencies.

@sebastianfrey  That is strange as the example apps are bundled to be self-contained in their corresponding packages. Can you also reproduce this issue locally?

**Comment by sebastianfrey** [comment]
@lucas-koehler Yes I can, when I run locally `npm run build:examples-app` to build the example apps, the issue is reproducible. Running the example app in dev mode with `cd packages/material-renderers && npm run dev` everything works fine. Maybe it has something to do with how rollup handles dependencies.

**Comment by sebastianfrey** [comment]
@lucas-koehler After a little bit more investigation it turns out, that the problem originates from the required @mui/material upgrade.

In detail the problem is because

b. how @mui/utils is published (Transpiled ES-Module)
c. how @mui/utils is leveraged in @mui/x-date-pickers 
d. how Rollup handles CommonJS default exports of transpile ES-Modules

It seems that https://github.com/rollup/plugins/issues/948 is related and that https://github.com/rollup/plugins/pull/1165 might fix it.

Unfortunately I have not the time right now to dig here deeper, maybe some of you guys might take a look?

**Comment by sebastianfrey** [comment]
Hi @lucas-koehler,

Here you go. Custom plugin and brief comment are pushed as requested. =)

**Comment by lucas-koehler** [comment]
Hi @sebastianfrey , thanks for the fixes and the effort :)
I'll have a closer look at the changes in June as I'm low on time right now.

**Review by lucas-koehler — APPROVED** [review]
Thanks for the updates, LGTM now :)

**Comment by sebastianfrey** [comment]
@lucas-koehler Just out of curiosity: What's the timeline for v3.1.0?

**Comment by sdirix** [comment]
The change is released as part of the `3.1.0-beta.0` which is available now

**Comment by sebastianfrey** [comment]
@sdirix @lucas-koehler Thanks for your effort and fast response. I appreciate this.
