### ISSUE TITLE
React 19 has no exported member 'ReducerAction'

### ISSUE THREAD

**Issue by artemchiruhin** [eclipsesource/jsonforms#2572]
### Describe the bug

In @jsonforms/react/src/JsonFormsContext.tsx, there is import `ReducerAction`, it works in React 18.3, but does not work in 19, because there is no such type (@types/react/index.d.ts)

### Expected behavior

Project build

### Steps to reproduce the issue

1. Set up project with react 19
2. Add
`"@jsonforms/core": "^3.7.0",
    "@jsonforms/react": "^3.7.0",`
3. Try to build the project
4. See error TS2305: Module '"react"' has no exported member 'ReducerAction'.

### Screenshots

<img width="1111" height="420" alt="Image" src="https://github.com/user-attachments/assets/32d52d25-91b4-4761-bc2c-c7e39ecb8de4" />

### Which Version of JSON Forms are you using?

3.5, 3.7

### Package

React Bindings
